version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    cooldown:
      default-days: 7
    groups:
      dev-dependencies:
        dependency-type: development
        update-types:
          - patch
          - minor
      production-dependencies:
        dependency-type: production
        update-types:
          - patch
          - minor
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    groups:
      github-actions:
        patterns:
          - '*'
