/**
 * @packageDocumentation
 * Build metadata for the bundled airport snapshot, exposed on its own
 * so consumers can report which cycle they are serving without decompressing
 * the records.
 *
 * Generated by `tools/build-airport-data`. Do not edit by hand.
 */

import type { AirportDatasetProperties } from './node.js';

/** Build metadata for the bundled airport snapshot. */
export const usBundledAirportsProperties: AirportDatasetProperties = {
  generatedAt: '2026-08-29T21:26:01.954Z',
  nasrCycleDate: '2026-09-03',
  recordCount: 19113,
};
