/**
 * @packageDocumentation
 * Build metadata for the bundled airport snapshot, exposed on its own
 * so consumers can report which cycle they are serving without decompressing
 * the records.
 *
 * Generated by `tools/build-airport-data`. Do not edit by hand.
 */

import type { AirportDatasetProperties } from './node.js';

/** Build metadata for the bundled airport snapshot. */
export const usBundledAirportsProperties: AirportDatasetProperties = {
  generatedAt: '2026-10-09T22:25:10.425Z',
  nasrCycleDate: '2026-10-29',
  recordCount: 19146,
};
