/**
 * @packageDocumentation
 * Build metadata for the bundled airspace snapshot, exposed on its own
 * so consumers can report which cycle they are serving without decompressing
 * the records.
 *
 * Generated by `tools/build-airspace-data`. Do not edit by hand.
 */

import type { AirspaceDatasetProperties } from './node.js';

/** Build metadata for the bundled airspace snapshot. */
export const usBundledAirspaceProperties: AirspaceDatasetProperties = {
  nasrCycleDate: '2026-09-03',
  generatedAt: '2026-08-29T21:26:39.632Z',
  featureCount: 6912,
};
