/**
 * @packageDocumentation
 * Build metadata for the bundled airspace snapshot, exposed on its own
 * so consumers can report which cycle they are serving without decompressing
 * the records.
 *
 * Generated by `tools/build-airspace-data`. Do not edit by hand.
 */

import type { AirspaceDatasetProperties } from './node.js';

/** Build metadata for the bundled airspace snapshot. */
export const usBundledAirspaceProperties: AirspaceDatasetProperties = {
  nasrCycleDate: '2026-10-29',
  generatedAt: '2026-10-10T17:29:25.228Z',
  featureCount: 6946,
};
