/**
 * @packageDocumentation
 * Build metadata for the bundled airway snapshot, exposed on its own
 * so consumers can report which cycle they are serving without decompressing
 * the records.
 *
 * Generated by `tools/build-airway-data`. Do not edit by hand.
 */

import type { AirwayDatasetProperties } from './node.js';

/** Build metadata for the bundled airway snapshot. */
export const usBundledAirwaysProperties: AirwayDatasetProperties = {
  generatedAt: '2026-10-09T22:25:13.123Z',
  nasrCycleDate: '2026-10-29',
  recordCount: 1515,
  waypointCount: 19081,
};
