/**
 * @packageDocumentation
 * Build metadata for the bundled airway snapshot, exposed on its own
 * so consumers can report which cycle they are serving without decompressing
 * the records.
 *
 * Generated by `tools/build-airway-data`. Do not edit by hand.
 */

import type { AirwayDatasetProperties } from './node.js';

/** Build metadata for the bundled airway snapshot. */
export const usBundledAirwaysProperties: AirwayDatasetProperties = {
  generatedAt: '2026-08-29T21:26:24.665Z',
  nasrCycleDate: '2026-09-03',
  recordCount: 1516,
  waypointCount: 19082,
};
