/**
 * @packageDocumentation
 * Build metadata for the bundled navaid snapshot, exposed on its own
 * so consumers can report which cycle they are serving without decompressing
 * the records.
 *
 * Generated by `tools/build-navaid-data`. Do not edit by hand.
 */

import type { NavaidDatasetProperties } from './node.js';

/** Build metadata for the bundled navaid snapshot. */
export const usBundledNavaidsProperties: NavaidDatasetProperties = {
  generatedAt: '2026-10-09T22:25:11.102Z',
  nasrCycleDate: '2026-10-29',
  recordCount: 1604,
};
