/**
 * @packageDocumentation
 * Build metadata for the bundled procedure snapshot, exposed on its own
 * so consumers can report which cycle they are serving without decompressing
 * the records.
 *
 * Generated by `tools/build-procedure-data`. Do not edit by hand.
 */

import type { ProcedureDatasetProperties } from './node.js';

/** Build metadata for the bundled procedure snapshot. */
export const usBundledProceduresProperties: ProcedureDatasetProperties = {
  generatedAt: '2026-10-09T22:44:25.949Z',
  cifpCycleDate: '2026-10-29',
  recordCount: 14302,
  sidCount: 2186,
  starCount: 1946,
  iapCount: 10170,
  legCount: 200853,
};
