/**
 * @packageDocumentation
 * Build metadata for the bundled procedure snapshot, exposed on its own
 * so consumers can report which cycle they are serving without decompressing
 * the records.
 *
 * Generated by `tools/build-procedure-data`. Do not edit by hand.
 */

import type { ProcedureDatasetProperties } from './node.js';

/** Build metadata for the bundled procedure snapshot. */
export const usBundledProceduresProperties: ProcedureDatasetProperties = {
  generatedAt: '2026-08-29T21:25:31.533Z',
  cifpCycleDate: '2026-09-03',
  recordCount: 14338,
  sidCount: 2190,
  starCount: 1916,
  iapCount: 10232,
  legCount: 201038,
};
