/**
 * @packageDocumentation
 * Build metadata for the bundled fix snapshot, exposed on its own
 * so consumers can report which cycle they are serving without decompressing
 * the records.
 *
 * Generated by `tools/build-fix-data`. Do not edit by hand.
 */

import type { FixDatasetProperties } from './node.js';

/** Build metadata for the bundled fix snapshot. */
export const usBundledFixesProperties: FixDatasetProperties = {
  generatedAt: '2026-10-09T22:25:12.405Z',
  nasrCycleDate: '2026-10-29',
  recordCount: 67583,
};
