/**
 * @packageDocumentation
 * Build metadata for the bundled fix snapshot, exposed on its own
 * so consumers can report which cycle they are serving without decompressing
 * the records.
 *
 * Generated by `tools/build-fix-data`. Do not edit by hand.
 */

import type { FixDatasetProperties } from './node.js';

/** Build metadata for the bundled fix snapshot. */
export const usBundledFixesProperties: FixDatasetProperties = {
  generatedAt: '2026-08-29T21:26:17.463Z',
  nasrCycleDate: '2026-09-03',
  recordCount: 67610,
};
